## Notebook para análise exploratória de dados

In [1]:
## Imports

import sys
from pathlib import Path

## ============================================
# Garante a leitura do modulo src 
project_root = Path.cwd().resolve().parents[1]
sys.path.append(str(project_root))


import pandas as pd
from src.data.reader import fetch_dataset

C:\Users\cadu2\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
## Leitura de dados

raw_data_dir = fetch_dataset()
csv_path = next(raw_data_dir.glob("*.csv"))
df = pd.read_csv(csv_path)
df.head()

,title,text,date,category,subcategory,link
0,"Lula diz que está 'lascado', mas que ainda tem...",Com a possibilidade de uma condenação impedir ...,2017-09-10,poder,NaN,http://www1.folha.uol.com.br/poder/2017/10/192...
1,"'Decidi ser escrava das mulheres que sofrem', ...","Para Oumou Sangaré, cantora e ativista malines...",2017-09-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
2,Três reportagens da Folha ganham Prêmio Petrob...,Três reportagens da Folha foram vencedoras do ...,2017-09-10,poder,NaN,http://www1.folha.uol.com.br/poder/2017/10/192...
3,Filme 'Star Wars: Os Últimos Jedi' ganha trail...,A Disney divulgou na noite desta segunda-feira...,2017-09-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
4,CBSS inicia acordos com fintechs e quer 30% do...,"O CBSS, banco da holding Elopar dos sócios Bra...",2017-09-10,mercado,NaN,http://www1.folha.uol.com.br/mercado/2017/10/1...

In [3]:
## Estrutura do DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 167053 entries, 0 to 167052
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   title        167053 non-null  str
 1   text         166288 non-null  str
 2   date         167053 non-null  str
 3   category     167053 non-null  str
 4   subcategory  29635 non-null   str
 5   link         167053 non-null  str
dtypes: str(6)
memory usage: 485.1 MB

Verificando categorias existentes

In [4]:
df["category"].value_counts()

category
poder                           22022
colunas                         21622
mercado                         20970
esporte                         19730
mundo                           17130
cotidiano                       16967
ilustrada                       16345
opiniao                          4525
paineldoleitor                   4011
saopaulo                         3955
tec                              2260
tv                               2142
educacao                         2118
turismo                          1903
ilustrissima                     1411
ciencia                          1335
equilibrioesaude                 1312
sobretudo                        1057
bbc                               980
folhinha                          876
empreendedorsocial                841
comida                            828
asmais                            548
ambiente                          491
seminariosfolha                   379
serafina                          334
o-melhor-de-sao-paulo             189
vice                              146
guia-de-livros-discos-filmes      143
topofmind                          86
banco-de-dados                     64
dw                                 48
especial                           43
cenarios-2017                      43
infograficos                       43
rfi                                29
guia-de-livros-filmes-discos       28
multimidia                         27
treinamento                        21
treinamentocienciaesaude           18
mulher                             16
euronews                            8
ombudsman                           3
contas-de-casa                      2
musica                              1
2016                                1
bichos                              1
2015                                1
Name: count, dtype: int64

Analisando dados ausentes

In [5]:
df[df["text"].fillna("").str.strip() == ""]

,title,text,date,category,subcategory,link
112,Quadrão,NaN,2017-09-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
216,Quadrinhos,NaN,2017-08-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
307,Quadrinhos,NaN,2017-07-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
471,Quadrinhos,NaN,2017-06-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
659,Quadrinhos,NaN,2017-05-10,ilustrada,NaN,http://www1.folha.uol.com.br/ilustrada/2017/10...
...,...,...,...,...,...,...
154165,"Ato contra falta de água ""escolta"" caminhão-pi...",NaN,2015-02-26,tv,cotidiano,http://www1.folha.uol.com.br/tv/cotidiano/2015...
158473,Avaliação Datafolha do prefeito Fernando Haddad,NaN,2015-07-02,infograficos,NaN,http://www1.folha.uol.com.br/infograficos/2015...
164808,"Quiz SP, 461",NaN,2015-09-01,infograficos,NaN,http://www1.folha.uol.com.br/infograficos/2015...
166243,Fundador do Atavist defende design especial pa...,NaN,2015-05-01,2015,NaN,http://novoemfolha.blogfolha.uol.com.br/2015/0...
166689,Calendário da Lola vai de 2014 para 2013; veja...,NaN,2015-03-01,folhinha,NaN,http://www1.folha.uol.com.br/folhinha/2015/01/...

Distribuição de category e subcategory (foco em nulos)

In [6]:
df["category"].value_counts(dropna=False)

category
poder                           22022
colunas                         21622
mercado                         20970
esporte                         19730
mundo                           17130
cotidiano                       16967
ilustrada                       16345
opiniao                          4525
paineldoleitor                   4011
saopaulo                         3955
tec                              2260
tv                               2142
educacao                         2118
turismo                          1903
ilustrissima                     1411
ciencia                          1335
equilibrioesaude                 1312
sobretudo                        1057
bbc                               980
folhinha                          876
empreendedorsocial                841
comida                            828
asmais                            548
ambiente                          491
seminariosfolha                   379
serafina                          334
o-melhor-de-sao-paulo             189
vice                              146
guia-de-livros-discos-filmes      143
topofmind                          86
banco-de-dados                     64
dw                                 48
especial                           43
cenarios-2017                      43
infograficos                       43
rfi                                29
guia-de-livros-filmes-discos       28
multimidia                         27
treinamento                        21
treinamentocienciaesaude           18
mulher                             16
euronews                            8
ombudsman                           3
contas-de-casa                      2
musica                              1
2016                                1
bichos                              1
2015                                1
Name: count, dtype: int64

In [7]:
df["subcategory"].value_counts(dropna=False)

subcategory
NaN                 137418
olimpiada-no-rio      2859
monicabergamo         2617
mercadoaberto         1035
eleicoes-2016          939
                     ...
samyadguirni             1
marceloninio             1
ricardo-mioto            1
rubensricupero           1
rogerioortega            1
Name: count, Length: 294, dtype: int64

In [8]:
df.groupby("category")["subcategory"].apply(lambda s: s.isna().mean()).sort_values(ascending=False)

category
2015                            1.000000
2016                            1.000000
ambiente                        1.000000
asmais                          1.000000
banco-de-dados                  1.000000
bbc                             1.000000
bichos                          1.000000
cenarios-2017                   1.000000
ciencia                         1.000000
comida                          1.000000
educacao                        1.000000
dw                              1.000000
folhinha                        1.000000
euronews                        1.000000
especial                        1.000000
equilibrioesaude                1.000000
vice                            1.000000
turismo                         1.000000
treinamentocienciaesaude        1.000000
rfi                             1.000000
guia-de-livros-filmes-discos    1.000000
guia-de-livros-discos-filmes    1.000000
ilustrada                       1.000000
ilustrissima                    1.000000
mundo                           1.000000
infograficos                    1.000000
mercado                         1.000000
mulher                          1.000000
musica                          1.000000
seminariosfolha                 1.000000
opiniao                         1.000000
ombudsman                       1.000000
serafina                        1.000000
treinamento                     1.000000
topofmind                       1.000000
tec                             1.000000
cotidiano                       0.997937
poder                           0.957361
paineldoleitor                  0.935178
saopaulo                        0.880910
esporte                         0.855094
empreendedorsocial              0.821641
o-melhor-de-sao-paulo           0.624339
contas-de-casa                  0.000000
colunas                         0.000000
multimidia                      0.000000
sobretudo                       0.000000
tv                              0.000000
Name: subcategory, dtype: float64

Análise de duplicatas

In [13]:
# Total de linhas e quantidade de valores distintos por coluna
print(f"Total de linhas: {len(df)}")
df.nunique()

Total de linhas: 167053

title          164119
text           165901
date              987
category           48
subcategory       293
link           167053
dtype: int64

In [14]:
# Para cada par de colunas (A, B): das linhas duplicadas em A, qual % também é duplicada em B
dup_masks = {col: df.duplicated(subset=[col], keep=False) for col in df.columns}

pd.DataFrame({
    col_b: {
        col_a: (mask_a & dup_masks[col_b]).sum() / mask_a.sum() if mask_a.sum() else float("nan")
        for col_a, mask_a in dup_masks.items()
    }
    for col_b in df.columns
})

                title      text  date  category  subcategory  link
title        1.000000  0.282939   1.0  1.000000     0.999253   0.0
text         0.834068  1.000000   1.0  0.997797     0.999266   0.0
date         0.024034  0.008153   1.0  0.999976     0.999868   0.0
category     0.024035  0.008135   1.0  1.000000     0.999868   0.0
subcategory  0.024019  0.008148   1.0  0.999976     1.000000   0.0
link              NaN       NaN   NaN       NaN          NaN   NaN